wrong variable (dt does not exist, it's Ts)
Trying to use c2d with method 'zoh' fails with:

```
Traceback (most recent call last):
  File "system_example.py", line 56, in <module>
    syst_fake_dis = c2d(syst_fake, 0.01, method='zoh')
  File "/usr/local/lib/python2.7/dist-packages/control-0.6d-py2.7.egg/control/matlab.py", line 1519, in c2d
    return sample_system(sysc, Ts, method)
  File "/usr/local/lib/python2.7/dist-packages/control-0.6d-py2.7.egg/control/dtime.py", line 87, in sample_system
    sysd = TransferFunction(scipySysD[0][0],scipySysD[1], dt)
NameError: global name 'dt' is not defined
```